# timescaledb: from-source via melange (PostgreSQL extension; time-series). Built
# Apache-only (-DAPACHE_ONLY=1, drops the TSL community-licensed code) against
# Wolfi's postgresql-17 and layered on top, like postgres-documentdb. The image
# version is the timescaledb extension version (e.g. 2.28.1). Tags are lightweight
# and point straight at the commit, so COMMIT pins each one (GitHub archive tarballs
# are not sha-stable; git-checkout + expected-commit is used for the same reason as
# documentdb). Latest 3 patches of the current 2.28 line.
FROM_SOURCE=1
VERSIONS=(2.28.1 2.28.2 2.28.3)
declare -A COMMIT=(
  [2.28.1]=b5b8e9b8f362d1559dc3de5eb32e4f309e891046
  [2.28.2]=558291fad04a71f255bdc0c67f1fa83385ff33a2
  [2.28.3]=4a77ff5cf1bf4348c4f0527e042434a289f06e39
)
render() { echo "s/__VER__/$1/g; s/__COMMIT__/${COMMIT[$1]}/g"; }
