# mosquitto (eclipse-mosquitto/mosquitto): from-source via melange (CMake build of
# the official mosquitto.org source tarball). MQTT broker. Ships the three newest
# patches of the current 2.1 line. (The 2.0 line is intentionally excluded: 2.0.x
# has no WITH_WEBSOCKETS_BUILTIN option — websockets there require external
# libwebsockets — and its man/CMakeLists errors even with docs off, so it diverges
# from the uniform 2.1 build.) Each release pins its tarball by sha256. Glibc-linked
# C; TLS via OpenSSL, websockets via the bundled builtin lib (no external
# libwebsockets), cJSON bundled (WITH_BUNDLED_DEPS). License: Eclipse dual EPL-2.0 / EDL-1.0.
FROM_SOURCE=1
VERSIONS=(2.1.0 2.1.1 2.1.2)
declare -A SHA256=(
  [2.1.0]=ceccf14f43b8ce21312d0dbf247025b8166536e9afba326f8b7c8b1d201fa6d9
  [2.1.1]=d93026a8f8255a32fe146ca77df5e26259b7947745370a3944a68ddb4ec663ff
  [2.1.2]=fd905380691ac65ea5a93779e8214941829e3d6e038d5edff9eac5fd74cbed02
)
render() { echo "s/__VER__/$1/g; s|__SHA256__|${SHA256[$1]}|g"; }
